version: "3"

services:

  jenkins:
    build: ./docker/jenkins
    networks:
      - pickem-net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./:/var/www/
      - ~/.ssh:/var/www/.ssh
      - ../jenkins_home/:/var/jenkins_home/

  web:
    build: ./docker/web
    networks:
      - pickem-net
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
          - "127.0.0.1:8088:80"

  lucee52:
    build: ./docker/lucee
    depends_on:
      - web
    networks:
      - pickem-net
    volumes:
      - ./:/var/www/
      - ~/.ssh:/var/www/.ssh

networks:
    pickem-net:
        driver: bridge
