version: "2"

services:
    db:
      build: ./docker/db
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - db:/var/lib/mysql

    jenkins:
      build: ./docker/jenkins
      environment:
        GITHUB_USERNAME: inquisibee
        GITHUB_CONFIG_REPOSITORY: https://github.com/inquisibee/jenkins-pickem.git


volumes:
  db:
