version: "2"

services:
    db:
      build: ./docker/db
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - db:/var/lib/mysql
      networks:
        - pickem-net

    jenkins:
      build: ./docker/jenkins
      networks:
        - pickem-net
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:50000:50000


volumes:
  db:


networks:
    pickem-net:
        driver: bridge
