version: "2"

services:
    db:
      build: ./docker/db
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - db:/var/lib/mysql
      networks:
        - pickem-net

volumes:
  db:


networks:
    pickem-net:
        driver: bridge
