version: "2"

services:
    db:
      build: ./docker/db
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./docker/db/pickem.cnf:/etc/mysql/conf.d/custom.cnf
        - ./data/db:/var/lib/mysql

    php:
      build: ./docker/php
      depends_on:
          - lucee52
      links:
          - lucee52
      working_dir: /var/www
      volumes:
          - ./:/var/www

    lucee52:
      build: ./docker/lucee
      depends_on:
        - db
      links:
        - db
      volumes:
        - ./:/var/www/
        - ~/.ssh:/var/www/.ssh

    nginx52:
      build: ./docker/nginx


    jenkins:
      image: jenkins:lts
      environment:
        JENKINS_OPTS="--prefix=/jenkins"
