version: "2"

services:
    db:
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: inqsports
        MYSQL_USER: inqsports
        MYSQL_PASSWORD: 1nquisib33
      ports:
        - "127.0.0.1:42306:3306"

    php:
      build: ./docker/php
      depends_on:
          - lucee52
      networks:
        - pickem-net
      working_dir: /var/www
      volumes:
          - ./:/var/www
      ports:
          - "127.0.0.1:8088:80"


    lucee52:
      build: ./docker/lucee
      depends_on:
        - db
      networks:
        - pickem-net
      volumes:
        - ./:/var/www/
        - ~/.ssh:/var/www/.ssh
      ports:
       - "8052:8888"

    nginx52:
      build: ./docker/nginx
      environment:
        - "VIRTUAL_HOST=nginx52.*"
      networks:
        - pickem-net

    jenkins:
        ports:
          - "127.0.0.1:8080:8080"
          - "127.0.0.1:50000:50000"
